services:
  server:
    # build:
    #   context: ./backend
    #   # todo: .env file
    #   args:
    #     BASE_URL: 0.0.0.0
    #     PORT: 8000
    #     ALLOWED_ORIGINS: http://localhost:4200
    image: server-test # todo: name
    environment:
      BASE_URL: 0.0.0.0
      PORT: 8000
      ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - '8000:8000'
    networks:
      - mustgofaster

  client:
    build:
      context: ./client
      args:
        BASE_URL: host.docker.internal:8000
      # todo: .env file
    image: client-test # todo: name
    environment:
      - BASE_URL=host.docker.internal:8000
    ports:
      - '4200:80'
    networks:
      - mustgofaster
    depends_on:
      - server

networks:
  mustgofaster:
    driver: bridge
