version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - '8000:8080'
    networks:
      - mustgofaster

  client:
    build:
      context: ./client
    ports:
      - '4200:80'
    networks:
      - mustgofaster
    depends_on:
      - server

networks:
  mustgofaster:
    driver: bridge
