services:
  server:
    build:
      context: ./backend
      args:
        BASE_URL: 0.0.0.0
        PORT: 8000
        ALLOWED_ORIGINS: http://localhost:4200
    image: must-go-faster-api
    container_name: backend
    environment:
      BASE_URL: 0.0.0.0
      PORT: 8000
      ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - '8000:8000'
    networks:
      - mustgofaster

  client:
    build:
      context: ./client
      args:
        API_BASE_URL: http://10.0.0.73:8000
        WS_BASE_URL: ws://10.0.0.73:8000
      # todo: .env file
    image: must-go-faster
    container_name: client
    environment:
      API_BASE_URL: http://host.docker.internal:8000
      WS_BASE_URL: ws://host.docker.internal:8000
    ports:
      - '4200:80'
    networks:
      - mustgofaster
    depends_on:
      - server

networks:
  mustgofaster:
    driver: bridge
