# FROM golang:1.21-alpine

# WORKDIR /app

# # Copy go mod and sum files
# COPY go.mod go.sum ./

# # Download dependencies
# RUN go mod download

# # Copy source code
# COPY . .

# # Build the application
# RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# # Use a smaller base image for the final image
# FROM alpine:latest

# WORKDIR /app

# # Copy the binary from builder
# COPY --from=0 /app/main .

# # Expose the port
# EXPOSE ${PORT:-8000}

# # Run the binary
# CMD ["./main"]