# CODEX-MODIFIED: the contents of this file were written by a human and modified after the fact by a Codex agent.
name: Build checks

on:
    pull_request:
        branches:
            - main

jobs:
    build-go:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go 1.21.x
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21.x
            - name: Build parser
              run: go build parser/parser.go
            - name: Build server
              run: go build server/server.go
            - name: Test server
              run: go test ./server/...

    build-js:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./client
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm
                  cache-dependency-path: client/package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test

