name: Do stuff

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup
        with:
          go-version: 1.21.5

      - name: Build
        run: go build parser/parser.go