# CODEX-MODIFIED: the contents of this file were written by a human and modified after the fact by a Codex agent.
name: Build checks

on:
    pull_request:
        branches:
            - main

jobs:
    build-go:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: ./.github/actions/setup-go
            - name: Build parser
              run: go build parser/parser.go
            - name: Build server
              run: go build server/server.go

    test-go:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: ./.github/actions/setup-go
            - name: Test server
              run: go test ./server/...

    build-js:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./client
        steps:
            - uses: ./.github/actions/setup-node
            - name: Build
              run: npm run build

    test-js:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./client
        steps:
            - uses: ./.github/actions/setup-node
            - name: Test
              run: npm run test

