name: Do stuff

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      name: Build parser
      with:
        go-version: 1.21.5
        run: go build -o parse.exe parser/parse.go